services:
  db:
    build:
      context: ./db
      dockerfile: db/Dockerfile
    image: mysql:8.0
    container_name: ${DB_CONTAINER_NAME}
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "${DB_PORT}:3306"
    volumes:
      - db-data:/var/lib/mysql
      - ./mysql:/docker-entrypoint-initdb.d
      - ./mysql/db.conf:/etc/db/conf.d/db.conf
    networks:
      - debukatu_network

  api:
    build:
      context: .
      dockerfile: go/Dockerfile
    container_name: ${BACKEND_CONTAINER_NAME}
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    depends_on:
      - db
    networks:
      - debukatu_network

volumes:
  db-data:


networks:
  debukatu_network:
    driver: bridge
