services:
  backend:
    build:
      context: ./go
    container_name: go-backend
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
    volumes:
      - ./go:/app
    working_dir: /app
    command: go run main.go

  db:
    build:
      context: ./docker/db/
      dockerfile: Dockerfile
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
      - ./mysql:/docker-entrypoint-initdb.d
      - ./mysql/db.conf:/etc/db/conf.d/db.conf
    networks:
      - debukatu_network

  api:
    build:
      context: .
      dockerfile: docker/app/Dockerfile
    env_file:
      - .env
    container_name: ${BACKEND_CONTAINER_NAME}
    ports:
      - "8081:80"
    environment:
      MYSQL_HOST: "${MYSQL_HOST}"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
    networks:
      - debukatu_network

volumes:
  db-data:
